install.packages("keras")
install.packages("kerasR")
install.packages("tidyverse")
install.packages("knitr")
install_keras()
library(tidyverse)
library(keras)
library(kerasR)
library(tidyverse)
library(knitr)
#To prevent the local unbound variabl error
library(tensorflow)
install_tensorflow(version="1.12")
mnist<-dataset_mnist()
cifar10 <- dataset_cifar10()
